apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: flux-system
  releaseName: flux
  chart:
    spec:
      chart: flux2
      version: 0.16.0
      sourceRef:
        kind: HelmRepository
        name: flux
        namespace: flux-system
