apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: flux2
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: flux-community
        namespace: flux-system
