apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k8s-homelab-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  # secretRef:
  #   name: github-secret
  url: ssh://git@github.com/adace123/k8s-homelab-pulumi

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: repos
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/repos
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-homelab-repo
  decryption:
    provider: sops
    secretRef:
      name: sops-age
