apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 1.87.7
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
  values:
    service:
      type: NodePort
    ports:
      web:
        port: 8000
        nodePort: 32500
