apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: repos
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/base/repos
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-homelab-repo
  decryption:
    provider: sops
    secretRef:
      name: sops-age
