apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.14.2
    chart: traefik
    helm:
      releaseName: traefik
      values: |
        service:
          type: NodePort
        ports:
          web:
            port: 8000
            nodePort: 32500
        experimental:
          kubernetesGateway:
            enabled: true
    kustomize:
      version: v4.5.4
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
