apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: traefik
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: 10.15.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
  values:
    logs:
      general:
        level: DEBUG
    service:
      type: NodePort
    ports:
      web:
        nodePort: 32500
    experimental:
      kubernetesGateway:
        enabled: true
    providers:
      kubernetesGateway:
      enabled: true
