apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  targetNamespace: vault
  releaseName: vault
  chart:
    spec:
      chart: vault
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
